cursor #e8e1dd
cursor_text_color #d1c5b8

foreground            #e8e1dd
background            #151311
selection_foreground  #382f23
selection_background  #d4c4b3
url_color             #dec29f

color0   #151311
color1   #ff7c72
color2   #81de6f
color3   #ffe672
color4   #d2b28b
color5   #664f31
color6   #dec29f
color7   #e9e3db
color8   #908b85
color9   #ffa59f
color10  #b4ffa5
color11  #ffefa5
color12  #f4dab9
color13  #ffe8cc
color14  #fff0de
color15  #fffcf8
